/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppSitesRouteRouteImport } from './routes/app/sites/route'
import { Route as AppSitesIndexRouteImport } from './routes/app/sites/index'
import { Route as AppOrganizationsIndexRouteImport } from './routes/app/organizations/index'
import { Route as AppSitesSlugRouteRouteImport } from './routes/app/sites/$slug/route'
import { Route as AppSitesSlugIndexRouteImport } from './routes/app/sites/$slug/index'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSitesRouteRoute = AppSitesRouteRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSitesIndexRoute = AppSitesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSitesRouteRoute,
} as any)
const AppOrganizationsIndexRoute = AppOrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSitesSlugRouteRoute = AppSitesSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppSitesRouteRoute,
} as any)
const AppSitesSlugIndexRoute = AppSitesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSitesSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/app/sites': typeof AppSitesRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/sites/$slug': typeof AppSitesSlugRouteRouteWithChildren
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/sites/': typeof AppSitesIndexRoute
  '/app/sites/$slug/': typeof AppSitesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/organizations': typeof AppOrganizationsIndexRoute
  '/app/sites': typeof AppSitesIndexRoute
  '/app/sites/$slug': typeof AppSitesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/logout': typeof LogoutRoute
  '/app/sites': typeof AppSitesRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/sites/$slug': typeof AppSitesSlugRouteRouteWithChildren
  '/app/organizations/': typeof AppOrganizationsIndexRoute
  '/app/sites/': typeof AppSitesIndexRoute
  '/app/sites/$slug/': typeof AppSitesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/logout'
    | '/app/sites'
    | '/auth/callback'
    | '/app/'
    | '/app/sites/$slug'
    | '/app/organizations'
    | '/app/sites/'
    | '/app/sites/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/auth/callback'
    | '/app'
    | '/app/organizations'
    | '/app/sites'
    | '/app/sites/$slug'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/logout'
    | '/app/sites'
    | '/auth/callback'
    | '/app/'
    | '/app/sites/$slug'
    | '/app/organizations/'
    | '/app/sites/'
    | '/app/sites/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/sites': {
      id: '/app/sites'
      path: '/sites'
      fullPath: '/app/sites'
      preLoaderRoute: typeof AppSitesRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sites/': {
      id: '/app/sites/'
      path: '/'
      fullPath: '/app/sites/'
      preLoaderRoute: typeof AppSitesIndexRouteImport
      parentRoute: typeof AppSitesRouteRoute
    }
    '/app/organizations/': {
      id: '/app/organizations/'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/sites/$slug': {
      id: '/app/sites/$slug'
      path: '/$slug'
      fullPath: '/app/sites/$slug'
      preLoaderRoute: typeof AppSitesSlugRouteRouteImport
      parentRoute: typeof AppSitesRouteRoute
    }
    '/app/sites/$slug/': {
      id: '/app/sites/$slug/'
      path: '/'
      fullPath: '/app/sites/$slug/'
      preLoaderRoute: typeof AppSitesSlugIndexRouteImport
      parentRoute: typeof AppSitesSlugRouteRoute
    }
  }
}

interface AppSitesSlugRouteRouteChildren {
  AppSitesSlugIndexRoute: typeof AppSitesSlugIndexRoute
}

const AppSitesSlugRouteRouteChildren: AppSitesSlugRouteRouteChildren = {
  AppSitesSlugIndexRoute: AppSitesSlugIndexRoute,
}

const AppSitesSlugRouteRouteWithChildren =
  AppSitesSlugRouteRoute._addFileChildren(AppSitesSlugRouteRouteChildren)

interface AppSitesRouteRouteChildren {
  AppSitesSlugRouteRoute: typeof AppSitesSlugRouteRouteWithChildren
  AppSitesIndexRoute: typeof AppSitesIndexRoute
}

const AppSitesRouteRouteChildren: AppSitesRouteRouteChildren = {
  AppSitesSlugRouteRoute: AppSitesSlugRouteRouteWithChildren,
  AppSitesIndexRoute: AppSitesIndexRoute,
}

const AppSitesRouteRouteWithChildren = AppSitesRouteRoute._addFileChildren(
  AppSitesRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppSitesRouteRoute: typeof AppSitesRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationsIndexRoute: typeof AppOrganizationsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSitesRouteRoute: AppSitesRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOrganizationsIndexRoute: AppOrganizationsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LogoutRoute: LogoutRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
